---
title: "DAVID Redone Code"
author: "Anusuiya Bora; s222331482@deakin.edu.au"
#output: html_document
output: 
  html_document:
    code_folding: show 
date: "2024-03-13"
---

### Methodology:
1. Loading libraries

```{r loading_libraries}

install.packages("pacman")  #this installs package. Only do once.

pacman::p_load(clusterProfiler,
               kableExtra,
               rio,           # package for importing and exporting data
               here,          # points R in particular directories to look for files;                          uses relative file paths; to tell R where our data is; used with "rio" package; good for relative file path
               dplyr,         # to manipulate data
               usethis,       # handy data cleaning functions
               gtsummary
)

```


2) Input gene list:

``` {r loading_input_genes}

genelist <- read.csv("PMC6587650.csv")
Genevec <- genelist[, 1]

```

3) Loading GO datsets

```{r include=FALSE, echo=FALSE, load_GORDS}

gobp <- rio::import(here::here("GO_dataset", "GObp.rds"))
gocc <- rio::import(here::here("GO_dataset", "GOcc.rds"))
gomf <- rio::import(here::here("GO_dataset", "GOmf.rds"))
gocombined <- rio::import(here::here("GO_dataset", "GOcombined.rds"))

#gobp <- readRDS("GObp.rds")
#gocc <- readRDS("GOcc.rds")
#gomf <- readRDS("GOmf.rds")
#gocombined <- readRDS("GOcombined.rds")

```


```{r include=FALSE, echo=FALSE, converting_RDS2gmt}
gobp_terms <- rev(stack(gobp))
str(gobp_terms)

gocc_terms <- rev(stack(gocc))
str(gocc_terms)

gomf_terms <- rev(stack(gomf))
str(gomf_terms)

gocombined_terms <- rev(stack(gocombined))
str(gocombined_terms)

#goterms <- rev(stack(golist))
#str(goterms)

```

5) Performing Enrichment analysis

```{r include=FALSE, echo=FALSE, enricher_code}
ora <- as.data.frame(enricher(gene = Genevec ,
                              maxGSSize = 50000, 
                              TERM2GENE = gocombined_terms, #for TERM2GENE, options are: gobp_terms, gocc_terms, gomf_terms, gocombined_terms
                              pAdjustMethod="fdr",  
                              pvalueCutoff = 1, 
                              qvalueCutoff = 1  ))

x <- gsub("/", " ", ora$geneID)
x
ora$geneID <- x

ora$ID <- NULL
rownames(ora) <- NULL

ora$S_No <- seq_len(nrow(ora))
ora <- ora[, c("S_No", names(ora)[-which(names(ora) == "S_No")])]

ora

```


6) Calculating enrichment scores

``` {r include=FALSE, echo=FALSE, ES_calculation}

ora$gene <- NULL
ora <- subset(ora,p.adjust<0.05 & Count >=10)
ora_s <- rownames(ora)

gr <- as.numeric(sapply(strsplit(ora$GeneRatio,"/"),"[[",1)) /
  as.numeric(sapply(strsplit(ora$GeneRatio,"/"),"[[",2))

br <- as.numeric(sapply(strsplit(ora$BgRatio,"/"),"[[",1)) /
  as.numeric(sapply(strsplit(ora$BgRatio,"/"),"[[",2))

es <- gr/br

ora_new <- cbind(ora, gr, br, es)

names(ora_new)[names(ora_new) == "es"] <- "EnrichmentScore"

ora_new

ora_fdr_arranged <- ora_new %>% 
  arrange(p.adjust)

```

7) Selecting pathways with FDR<0.05

```{r pathways_FDR}

ora_fdr <- ora_fdr_arranged %>%
  filter(p.adjust < 0.05)

```


```{r output_table}

ora_fdr %>%
  kbl(caption="Genes and GO Terms identified") %>%
  kable_paper("hover", full_width = F)

```


## Session information

For reproducibility.

```{r,sessioninfo}

sessionInfo()

```

```{r github_upload}

##gitcreds_set()
##git clone (https://github.com/anusuiyaxbora/DAVID_Reborn.git)

```